const employee=[
    {
      id: 1,
      name: "Jakaria",
      username: "Bret",
      email: "Sincere@april.biz",
      yearlysalary : 500000,
      image : 'https://www.pexels.com/photo/man-crossed-arms-1516680/',
      address:"Kulas Light, Apt. 556, city: Gwenborough",
      phone: "1-770-736-8031 x56442",
      website: "hildegard.org",
      },
      {
        id: 2,
        name: "Ervin Howell",
        username: "Antonette",
        email: "Shanna@melissa.tv",
        yearlysalary : 56460000,
        image : 'https://www.pexels.com/photo/photography-of-a-guy-wearing-green-shirt-1222271/',
        address:"Kulas Light, Apt. 556, city: Gwenborough",
        phone: "010-692-6593 x09125",
        website: "anastasia.net",
        },
    
    {
        id: 3,
        name: "Clementine Bauch",
        username: "Samantha",
        email: "Nathan@yesenia.net",
        yearlysalary : 45200144,
        image : 'https://www.pexels.com/photo/business-businessman-contemporary-corporate-532220/',
        address:"Kulas Light, Apt. 556, city: Gwenborough",
        phone: "1-463-123-4447",
        website: "ramiro.info",
    },
    {
        id: 4,
        name: "Patricia Lebsack",
        username: "Karianne",
        email: "Julianne.OConner@kory.org",
        yearlysalary : 58824441,
        image : 'https://www.pexels.com/photo/man-wearing-a-jacket-sitting-on-brown-wooden-crate-594610',
        address:"Kulas Light, Apt. 556, city: Gwenborough",
        phone: "493-170-9623 x156",
        website: "kale.biz",
    },
    {
        id: 5,
        name: "Chelsey Dietrich",
        username: "Kamren",
        email: "Lucio_Hettinger@annie.ca",
        yearlysalary : 4238524,
        image :  'https://www.pexels.com/photo/portrait-photo-of-smiling-man-with-his-arms-crossed-standing-in-front-of-white-wall-2379004/',
        address:"Kulas Light, Apt. 556, city: Gwenborough",
        phone: "(254)954-1289",
        website: "demarco.info",
    },
    {
        id: 6,
        name: "Mrs. Dennis Schulist",
        username: "Leopoldo_Corkery",
        email: "Karley_Dach@jasper.info",
        yearlysalary : 5432582,
        image : 'https://www.pexels.com/photo/men-s-wearing-black-suit-jacket-and-pants-937481/',
        address:"Kulas Light, Apt. 556, city: Gwenborough",
        phone: "1-477-935-8478 x6430",
        website: "ola.org",
    },
    {
        id: 7,
        name: "Kurtis Weissnat",
        usernam: "Elwyn.Skiles",
        email: "Telly.Hoeger@billy.biz",
        yearlysalary : 6534245,
        image : 'https://www.pexels.com/photo/man-holding-white-teacup-in-front-of-gray-laptop-842567/',
        address:"Kulas Light, Apt. 556, city: Gwenborough",
        phone: "210.067.6132",
        website: "elvis.io",
    },
    {
        id: 8,
        name: "Nicholas Runolfsdottir V",
        username: "Maxime_Nienow",
        email: "Sherwood@rosamond.me",
        yearlysalary : 6587452,
        image : 'https://www.pexels.com/photo/adult-black-and-white-dark-face-412840/',
        address:"Kulas Light, Apt. 556, city: Gwenborough",
        phone: "586.493.6943 x140",
        website: "jacynthe.com",
    },
    {
        id: 9,
        name: "Glenna Reichert",
        username: "Delphine",
        email: "Chaim_McDermott@dana.io",
        yearlysalary : 4578445,
        image : 'https://www.pexels.com/photo/man-wearing-brown-dress-shirt-holding-white-fedora-hat-1036627/',
        address:"Kulas Light, Apt. 556, city: Gwenborough",
        phone: "(775)976-6794 x41206",
        website: "conrad.com",
    },
    {
        id: 10,
        name: "Clementina DuBuque",
        username: "Moriah.Stanton",
        email: "Rey.Padberg@karina.biz",
        yearlysalary : 785575,
        image : 'https://www.pexels.com/photo/man-doing-pose-1496647/',
        address:"Kulas Light, Apt. 556, city: Gwenborough",
        phone: "024-648-3804",
        website: "ambrose.net",
    },
  ]
  export default employee;